theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache
gems:
  - jekyll-last-modified-at
google_site_verification: HtqjvGpOO7zMqHjzMmE6bM658bRZqGQewz_h-QyRnns
social:
  name: Yoni Leibowitz
  links:
    - https://www.linkedin.com/in/yonileibo/